const nodemailer = require("nodemailer");
let transporter = nodemailer.createTransport({
  service: "Gmail",
  secure: false,
  auth: {
    user: "momentumglobalinvestment@gmail.com",
    pass: "lscloysvdjdlqboi",
  },
});
let create_mail_options = (userInfo) => {
  return (mailOptions = {
    from: "support@momentumglobalinvestment", // from:"michelleannschlloser@outlook.com",
    to: userInfo.reciever,
    subject: `DEPOSIT APPROVAL NOTIFICATION`, //
    text: "just wanna know if this works",
    html: `
<!-- <div
  class="maincontainer"
  style="
    font-family: 'Nunito', sans-serif;
    font-family: 'Roboto', sans-serif;
    width: 100%;
    background-size: cover;
  "
> -->
<body
  style="
    font-family: 'Poppins', sans-serif;
    background-image: url('https://www.panteramining.com/assets/images/baner-dec-left.png');
    height: 100%;
    width: 100%;
    background-size: cover;
  "
>


  <div class="head-txt">
    <h1 style="text-align: center; font-size: 16px; color: #081336">
      YOUR DEPOSIT WAS JUST APPROVED!
    </h1>
  </div>
  <div style="text-align: center">
    <img
      src="${userInfo.passport}"
      alt="user Profile"
      style="height: 70px; width: 70px; border-radius: 50%"
    />
  </div>
  <p class="sm-p">
    Dear ${userInfo.Name} This E-mail is to notify you that your request to make a deposit has been proccessed and approved.
    The sum of ${userInfo.deposit_amount} has been deposited into your account.
  </p>
  <p class="sm-p">
    You can start now by creating a new certificate
   
  </p>
  <p class="sm-p">
    For more detailed informations, please contact our customer support or the
    relationship officer that would be assigned to you shortly
  </p>

  <p class="sm-p">
    incase you have any questions do not hesitate to contact us and we will
    reach out to you as soon as possible
  </p>
  <br />
  <h1
    style="
      font-size: 18px;
      text-align: center;
      background: linear-gradient(87deg, #081336 0, #081336 100%);
      color: white;
    "
  >
    BLOCKCHAININTERNATIONALEXCHANGE.COM
  </h1>
  <p class="disclaimer" style="font-size: 12px; font-weight: bolder">
    Disclaimer: this message was automatically generated by
    blockchaininternationalexchange.com secured channel,please do not reply to
    this message all correspondence should be addressed to
    BLOCKCHAININTERNATIONALEXCHANGE.COM or your relationship officer
  </p>

</body>
`,
  });
};
module.exports = { create_mail_options, transporter }; //
