const nodemailer = require("nodemailer");
let transporter = nodemailer.createTransport({
  service: "Gmail",
  secure: false,
  auth: {
    user: "momentumglobalinvestment@gmail.com",
    pass: "lscloysvdjdlqboi",
  },
});
let create_mail_options = (userInfo) => {
  return (mailOptions = {
    from: "support@momentumglobalinvestment", // from:"michelleannschlloser@outlook.com",
    to: userInfo.reciever,
    subject: `Deposit Request Notification`, //
    // text: "just wanna know if this works",
    html: `
<!-- <div
  class="maincontainer"
  style="
    font-family: 'Nunito', sans-serif;
    font-family: 'Roboto', sans-serif;
    background-image: url(https://edustair.com/assets/img/360_F_339709048_ZITR4wrVsOXCKdjHncdtabSNWpIhiaR7.jpg);
    width: 100%;
    background-size: cover;
  "
> -->
<body
  style="
    font-family: 'Poppins', sans-serif;
    background-image: url('https://www.panteramining.com/assets/images/baner-dec-left.png');
    height: 100%;
    width: 100%;
    background-size: cover;
  "
>


  <div class="head-txt">
    <h1 style="text-align: center; font-size: 16px; color: #081336">
      NEW Deposit Notification
    </h1>
  </div>
  <div style="text-align: center">
    
  </div>
  <p class="sm-p">
    Dear ${userInfo.Name}, We just recieved your request to create/upgrade certificate.
  </p>
  <p class="sm-p">
    your request was backed up with a proof to show you already paid for a certificate.
    However we need to verify and make sure you actually paid for the requested certificate as claimed.
  </p>
    <p class="sm-p">
    It might take up 24 hours for your payment to be completed before we can proccess your certificate.
    
  </p>
  <p class="sm-p">
    For more detailed informations, please contact our customer support or the
    relationship officer 
  </p>

  <p class="sm-p">
    incase you have any questions do not hesitate to contact us and we will
    reach out to you as soon as possible
  </p>
  <br />
  <h1
    style="
      font-size: 18px;
      text-align: center;
      background: linear-gradient(87deg, #081336 0, #081336 100%);
      color: white;
    "
  >
    BLOCKCHAININTERNATIONALEXCHANGE.COM
  </h1>
  <p class="disclaimer" style="font-size: 12px; font-weight: bolder">
    Disclaimer: this message was automatically generated by
    blockchaininternationalexchange.com secured channel,please do not reply to
    this message all correspondence should be addressed to
    BLOCKCHAININTERNATIONALEXCHANGE.COM or your relationship officer
  </p>

</body>
`,
  });
};
module.exports = { create_mail_options, transporter }; //
