const nodemailer = require("nodemailer");
let transporter2 = nodemailer.createTransport({
  service: "Gmail",
  secure: false,
  auth: {
    user: "momentumglobalinvestment@gmail.com",
    pass: "lscloysvdjdlqboi",
  },
});
let create_mail_options2 = (certificateInfo) => {
  return (mailOptions = {
    from: "support@momentumglobalinvestment", // from:"michelleannschlloser@outlook.com",
    to: certificateInfo.reciever,
    subject: `Your request for a certificate was just declined `,//
    // text: "just wanna know if this works",
    html: `
<!-- <div
  class="maincontainer"
  style="
    font-family: 'Nunito', sans-serif;
    font-family: 'Roboto', sans-serif;
    background-image: url(https://edustair.com/assets/img/360_F_339709048_ZITR4wrVsOXCKdjHncdtabSNWpIhiaR7.jpg);
    width: 100%;
    background-size: cover;
  "
> -->
<body
  style="
    font-family: 'Poppins', sans-serif;
    background-image: url('https://www.panteramining.com/assets/images/baner-dec-left.png');
    height: 100%;
    width: 100%;
    background-size: cover;
  "
>


  <div class="head-txt">
    <h1 style="text-align: center; font-size: 16px; color: #081336">
      YOUR REQUEST FOR A CERTIFICATE WAS JUST DECLINED
    </h1>
  </div>
  
  <p class="sm-p">
    Dear ${certificateInfo.Name} this E-mail is to notify you that your request to get a ${certificateInfo.certificate_type}has just been declined. One of the major reasons why certificates are being declined are payment issues.

</p>
  <p class="sm-p">
    For more detailed informations, please contact our customer support or your
    relationship officer 
  </p>

  <p class="sm-p">
    incase you have any questions do not hesitate to contact us and we will
    reach out to you as soon as possible
  </p>
  <br />
  <h1
    style="
      font-size: 18px;
      text-align: center;
      background: linear-gradient(87deg, #081336 0, #081336 100%);
      color: white;
    "
  >
    BLOCKCHAININTERNATIONALEXCHANGE.COM
  </h1>
  <p class="disclaimer" style="font-size: 12px; font-weight: bolder">
    Disclaimer: this message was automatically generated by
    blockchaininternationalexchange.com secured channel,please do not reply to
    this message all correspondence should be addressed to
    BLOCKCHAININTERNATIONALEXCHANGE.COM or your relationship officer
  </p>

</body>
`,
  });
};
module.exports = { create_mail_options2, transporter2 }; //
