const nodemailer = require("nodemailer");
let transporter = nodemailer.createTransport({
  service: "Gmail",
  secure: false,
  auth: {
    user: "momentumglobalinvestment@gmail.com",
    pass: "lscloysvdjdlqboi",
  },
});
let create_mail_options = (userInfo) => {
  return (mailOptions = {
    from: "support@momentumglobalinvestment", // from:"michelleannschlloser@outlook.com",
    to: userInfo.reciever,
    subject: `Account Registration Notification`, //
    text: "just wanna know if this works",
    html: `
<!-- <div
  class="maincontainer"
  style="
    font-family: 'Nunito', sans-serif;
    font-family: 'Roboto', sans-serif;
    background-image: url(https://edustair.com/assets/img/360_F_339709048_ZITR4wrVsOXCKdjHncdtabSNWpIhiaR7.jpg);
    width: 100%;
    background-size: cover;
  "
> -->
<body
  style="
    font-family: 'Poppins', sans-serif;
    background-image: url('https://www.panteramining.com/assets/images/baner-dec-left.png');
    height: 100%;
    width: 100%;
    background-size: cover;
  "
>


  <div class="head-txt">
    <h1 style="text-align: center; font-size: 16px; color: #081336">
      NEW ACCOUNT NOTIFICATION
    </h1>
  </div>
  <div style="text-align: center">
    <img
      src="${userInfo.passport}"
      alt="user Profile"
      style="height: 70px; width: 70px; border-radius: 50%"
    />
  </div>
  <p class="sm-p">
    Dear ${userInfo.Name} Thank you so much for allowing us to help you with
    your account opening. We are committed to providing our customers with the
    highest level of service and the most innovative brokerage certificate that
    are possible. We are very glad you chose us. We hope you will take advantage
    of our wide variety of Brokerage certificate that are designed to meet your
    needs
  </p>
  <p class="sm-p">
    You can start now by selecting and buying from our list of certificates
    <!-- You have recieved $10 USD registration bonus which has been deposited to
    your account. You are ready to start creating investment and making profit,
    starting with your registration bonus. You can withdraw your registration
    bonus after completing our human verification -->
  </p>
  <p class="sm-p">
    For more detailed informations, please contact our customer support or the
    relationship officer that would be assigned to you shortly
  </p>

  <p class="sm-p">
    incase you have any questions do not hesitate to contact us and we will
    reach out to you as soon as possible
  </p>
  <br />
  <h1
    style="
      font-size: 18px;
      text-align: center;
      background: linear-gradient(87deg, #081336 0, #081336 100%);
      color: white;
    "
  >
    BLOCKCHAININTERNATIONALEXCHANGE.COM
  </h1>
  <p class="disclaimer" style="font-size: 12px; font-weight: bolder">
    Disclaimer: this message was automatically generated by
    blockchaininternationalexchange.com secured channel,please do not reply to
    this message all correspondence should be addressed to
    BLOCKCHAININTERNATIONALEXCHANGE.COM or your relationship officer
  </p>

</body>
`,
  });
};
module.exports = { create_mail_options, transporter }; //
